#!/usr/bin/env python3
# SPDX-License-Identifier: BUSL-1.1
#
# SoothingSpaces EMDR safe-space session runner
# Copyright (C) 2026 Mark J. Kuebel
"""Run an EMDR safe-space session and drive Omara with a scent keyframe track.

    start_session.bat / py session.py [options]

The runner owns the whole therapy loop:

  1. Intake     — asks what the client's safe space IS, then walks the senses
                  (sight, sound, smell, touch/temperature) and the feeling it
                  gives, with follow-ups until there is real material to work
                  with (a substantial session asks enough questions that a
                  stranger could see themselves into the scene).
  2. Build      — DEFAULT (--keyframes 1): ONE scent mix for the scene, up to
                  MIX_SIZE channels each with its own intensity, generated by
                  the local model from the client's own words (rule-based
                  fallback when no model server is up). --keyframes N keeps
                  the multi-frame option: an N-frame keyframe sequence at a
                  2-second interval (~60 s breathing-paced for N=30), one mix
                  per frame.
  3. Deliver    — sends each mix to the omara bridge over its WebSocket port
                  as ONE spray command: every channel of the mix fires in one
                  packet, each at its own intensity (the bridge caps a packet
                  at MAX_SCENTS=3 and resolves names against loaded tubes).
  4. Remember   — the calculated scent plus the scene answers are saved to
                  safe_space.json. The next run finds that file and asks if
                  you would like to RETURN TO YOUR SAFE SPACE: yes re-sprays
                  the saved mix and reminds you what you told it; no starts a
                  fresh intake. --skip-recall ignores the file entirely.

A local model server (Unsloth Studio llama.cpp or Ollama, OpenAI-compatible)
powers mix generation. If it is down, session.py falls back to palette-aware
rule-based mixes from the client's named smells, so a session never dies on
an LLM outage. --no-model skips the model entirely and uses that path.

Options below; run with --help. This program prints only what the client
types in this console — nothing leaves the machine except loopback traffic.
"""
from __future__ import annotations

import argparse
import json
import os
import sys
import time

from sniff import (Sniffer, VALID_ODORS, intensity_curve, keep_strongest,
                   normalize_mix)

try:
    from websockets.sync.client import connect as ws_connect
except ImportError:          # only needed when actually reaching the bridge
    ws_connect = None

DEFAULT_KEYFRAMES = 1       # single mix for the scene, one spray per channel
FRAME_COUNT = 30            # classic multi-frame track length (--keyframes 30)
MAX_KEYFRAMES = 240         # sanity clamp on --keyframes
FRAME_INTERVAL = 2.0        # seconds between keyframes (~60 s for 30 frames)
MIX_SIZE = 3                # scents per mix; bridge caps one packet at 3

_HERE = os.path.dirname(os.path.abspath(__file__))
SAFE_SPACE_FILE = os.path.join(_HERE, "safe_space.json")


# ───────────────────────────── console helpers ───────────────────────────────
def say(msg: str = "") -> None:
    print(msg, flush=True)

_EOF_SEEN = False     # set once stdin hits EOF so no prompt ever spins on it


def wrap(text: str, width: int = 72) -> str:
    out, line = [], ""
    for word in text.split():
        if len(line) + len(word) + (1 if line else 0) > width:
            out.append(line)
            line = word
        else:
            line = (line + " " + word).strip()
    if line:
        out.append(line)
    return "\n".join(out)

def ask(prompt: str, *, required: bool = True, allow_quit: bool = True) -> str:
    """One console question. 'skip' answers optional ones; blank re-asks on
    required ones so a session never builds on an empty answer. EOF (closed
    stdin) returns '' and marks the input exhausted so callers wind down
    instead of looping forever."""
    global _EOF_SEEN
    while True:
        if _EOF_SEEN:
            return ""
        try:
            ans = input(prompt).strip()
        except EOFError:
            _EOF_SEEN = True
            say("\n(input closed — ending intake; the session will use what it has)")
            return ""
        low = ans.lower()
        if allow_quit and low in ("quit", "exit", "q"):
            raise KeyboardInterrupt
        if ans:
            return ans
        if not required:
            return ""
        say("  (please type an answer, or 'quit' to end the session)")

def confirm(prompt: str, default_yes: bool = True) -> bool:
    hint = "Y/n" if default_yes else "y/N"
    ans = ask(f"{prompt} [{hint}] ", required=False).lower()
    if not ans:
        return default_yes
    return ans in ("y", "yes")


# ─────────────────────────────── intake ──────────────────────────────────────
# Each step: (question, key, required, follow-up-question-or-None).
# The follow-up only fires when the first answer is short — a one-word answer
# means there is more in there, and a substantial safe space needs detail.
INTAKE_STEPS = [
    ("Think of a place where you feel completely safe and at ease. It can be "
     "real or imagined. Where are you?", "place", True,
     "Paint it for me: what do you see around you right now in that place?"),
    ("What do you HEAR there?", "sound", True,
     "Anything quieter underneath that sound — wind, water, birds, a room's hush?"),
    ("Now the most important one: what do you SMELL there? Real or imagined "
     "smells both count.", "smell", True,
     "Any other smell in that place — something from a person, food, nature, "
     "wood, rain? Name as many as come."),
    ("What do you FEEL on your skin there — warmth, breeze, sun, a blanket?",
     "touch", False, None),
    ("Who is with you in this place, or are you alone?", "company", True,
     "What makes being with them (or being alone) feel safe?"),
    ("When you are in this place, what feeling fills you up?", "emotion", True,
     "Where do you feel that in your body — chest, shoulders, belly? Hold that."),
    ("If this place had one color and one time of day, what would they be?",
     "color_time", False, None),
]

CALM_SCALE = ("On a scale of 1 to 10, how calm and safe do you feel picturing "
              "this place right now?")


def run_intake() -> dict:
    say()
    say(wrap("Welcome. This session builds your SAFE PLACE: a scene you choose, "
             "reinforced with gentle scents chosen from your own words. Answer "
             "in your own words; there are no wrong answers. Type 'quit' at any "
             "question to stop."))
    say()
    profile: dict = {}
    for i, (q, key, required, follow) in enumerate(INTAKE_STEPS, 1):
        say(f"[{i}/{len(INTAKE_STEPS)}] {wrap(q)}")
        ans = ask("   > ", required=required)
        if not ans and not required:
            continue
        if follow and len(ans) < 40:            # short answer: dig once more
            say(wrap(f"   {follow}"))
            more = ask("   > ", required=False)
            if more:
                ans = f"{ans}. {more}"
        profile[key] = ans
    say()
    calm = 5                                   # neutral default if input ends
    while True:
        say(wrap(CALM_SCALE))
        raw = ask("   > ", required=True, allow_quit=False)
        if not raw:                              # EOF: wind down on the default
            break
        try:
            calm = max(1, min(10, int(float(raw.split()[0]))))
            break
        except (ValueError, IndexError):
            say("   (a number from 1 to 10)")
    profile["calm"] = calm
    if not confirm("Good. Build the safe-space scent sequence from this?", True):
        raise KeyboardInterrupt
    return profile


# ──────────────────────── keyframe track construction ────────────────────────
def frame_prompt(profile: dict, idx: int, total: int) -> str:
    """One frame's 'moment' text for the mix model: same scene, different
    facet emphasis, so the 30 frames feel like a slow pan, not one still."""
    phase = "settling in" if idx < total * 0.34 else \
            ("being held by the place" if idx < total * 0.67 else "leaving with it")
    facets = ["sight", "sound", "smell", "touch", "company", "emotion"]
    facet_a = facets[idx % len(facets)]
    facet_b = facets[(idx // len(facets)) % len(facets) or 0]
    parts = [f"Safe place: {profile.get('place', '')}"]
    for key, label in (("sound", "Sounds"), ("smell", "Smells"),
                       ("touch", "Feels"), ("company", "Company"),
                       ("color_time", "Light and color")):
        if profile.get(key):
            parts.append(f"{label}: {profile[key]}")
    parts.append(f"Feeling: calm level {profile.get('calm', 5)}/10")
    parts.append(f"Frame {idx + 1}/{total} ({phase}); lean toward the "
                 f"{facet_a} and {facet_b} of the scene.")
    return "\n".join(parts)


def scene_hits(profile: dict) -> list[dict]:
    """Every palette cartridge the client's own words point at, strongest
    first, each carrying its cause string. This is the track's scent pool:
    wider than one frame's mix, and what keeps a dominant smell from leading
    all thirty frames."""
    text = " ".join(str(profile.get(k, "")) for k in
                    ("smell", "place", "sound", "touch", "company", "emotion")).lower()
    anchors: list[dict] = []

    def hit(words: list[str], odor: str, base: float) -> None:
        for w in words:
            if w in text:
                anchors.append({"odor": odor, "intensity": round(base, 3),
                                "why": f"you named '{w}'"})
                return

    hit(["ocean", "sea", "beach", "coast", "wave", "salt"], "marine", 0.9)
    hit(["rain", "storm", "wet", "petrichor"], "petrichor", 0.85)
    hit(["pine", "forest", "woods", "fir", "tree", "cabin", "evergreen"],
        "evergreen", 0.85)
    hit(["flower", "garden", "blossom", "meadow", "lavender", "rose"],
        "floral", 0.8)
    hit(["wood", "timber", "cedar", "log"], "timber", 0.8)
    hit(["cookie", "bake", "cook", "food", "kitchen", "sweet", "chocolate"],
        "sweet", 0.8)
    hit(["spice", "cinnamon", "ginger", "curry"], "savory_spice", 0.75)
    hit(["citrus", "lemon", "orange", "sunny"], "citrus", 0.7)
    hit(["snow", "cold", "winter", "ice", "frost"], "winter", 0.7)
    hit(["desert", "sand", "canyon", "dry", "stars"], "desert", 0.7)
    hit(["river", "moss", "earth", "soil", "creek", "mud"], "terra_silva", 0.75)
    hit(["sunscreen", "tropical", "island"], "beach", 0.8)
    hit(["mother", "dad", "father", "friend", "partner", "wife", "husband",
         "hold", "held", "hug", "family", "baby", "dog", "cat", "pet"],
        "kindred", 0.9)
    hit(["fire", "campfire", "fireplace", "smoke"], "smoky", 0.6)
    hit(["ranch", "farm", "barn", "horse", "cow", "goat", "chicken", "stable"],
        "barnyard", 0.85)
    return normalize_mix(anchors)


def rule_mix(profile: dict, idx: int = 0, total: int = 1, *,
             apply_curve: bool = True) -> list[dict]:
    """Model-free fallback mix: the client's strongest named smells, curved
    across the track. Same shape as a model answer so downstream is identical.
    apply_curve=False keeps the base intensities (single-mix mode has no track
    to curve)."""
    anchors = scene_hits(profile)
    for filler, strength in (("kindred", 0.5), ("sweet", 0.35), ("floral", 0.25)):
        if len(anchors) >= MIX_SIZE:
            break
        if all(a["odor"] != filler for a in anchors):
            anchors = normalize_mix(
                anchors + [{"odor": filler, "intensity": strength,
                            "why": "calm default"}])
    # Slow fade: shape the whole frame's intensity across the track so the
    # strongest hits land mid-sequence instead of flatlining at full blast.
    curve = intensity_curve(idx, total) if apply_curve else 1.0
    for s in anchors:
        s["intensity"] = round(max(0.1, min(1.0, s["intensity"] * curve)), 3)
    return normalize_mix(anchors)[:MIX_SIZE]


def scene_prompt(profile: dict) -> str:
    """The whole scene as one moment for the mix model — no frame phasing."""
    parts = [f"Safe place: {profile.get('place', '')}"]
    for key, label in (("sound", "Sounds"), ("smell", "Smells"),
                       ("touch", "Feels"), ("company", "Company"),
                       ("color_time", "Light and color")):
        if profile.get(key):
            parts.append(f"{label}: {profile[key]}")
    parts.append(f"Feeling: calm level {profile.get('calm', 5)}/10")
    return "\n".join(parts)


def build_scene_mix(profile: dict, sniffer: Sniffer | None) -> list[dict]:
    """DEFAULT mode (--keyframes 1): ONE mix for the scene — up to MIX_SIZE
    channels, each with its own intensity. Model first; palette rules over the
    client's named smells when it is down."""
    mix: list[dict] | None = None
    if sniffer is not None:
        try:
            mix = sniffer.sniff_mix(scene_prompt(profile), n=MIX_SIZE)
        except Exception as exc:
            say(f"  model mix failed ({exc}); rule fallback")
    if not mix:
        return rule_mix(profile, apply_curve=False)
    return normalize_mix(mix)[:MIX_SIZE]


def build_track(profile: dict, sniffer: Sniffer | None,
                frame_count: int = FRAME_COUNT) -> list[dict]:
    """`frame_count` keyframes at FRAME_INTERVAL seconds; each frame carries a
    MIX_SIZE-scent mix. Model mixes per frame with a rule-based rescue when
    the model is unreachable for that frame. The whole track then gets the
    intensity curve so both paths breathe the same way.

    Each frame also records `cause`: what in the scene put the lead scent
    there, shown at emission time so you can follow the sequence as a story
    rather than a list of cartridge names."""
    frames: list[dict] = []
    failed_frames = 0
    pool = scene_hits(profile)          # wider than one mix; feeds diversity
    recent_leads: list[str] = []        # fed to the prompt as don't-repeat hints
    last_lead: str | None = None        # never spray the same scent twice running
    lead_counts: dict[str, int] = {}    # per-scent lead tally for round-robin
    for idx in range(frame_count):
        prompt = frame_prompt(profile, idx, frame_count)
        used = list(dict.fromkeys(recent_leads))[-4:]
        mix: list[dict] | None = None
        if sniffer is not None:
            try:
                mix = sniffer.sniff_mix(prompt, n=MIX_SIZE, recent_leads=used)
            except Exception as exc:
                say(f"  model frame {idx + 1} failed ({exc}); rule fallback")
                mix = None
            if mix is None:
                failed_frames += 1
        if not mix:
            mix = rule_mix(profile, idx, frame_count)   # already curved there
        else:
            curve = intensity_curve(idx, frame_count)
            for s in mix:
                s["intensity"] = round(max(0.1, min(1.0, s["intensity"] * curve)), 3)
            mix = normalize_mix(mix)[:MIX_SIZE]
        # Code-side diversity guarantee: prompt steering alone loses to a
        # dominant scene smell at temperature 0, so the lead gets balanced
        # here. If this frame's lead is the same as the previous one, or has
        # led recently, promote whichever candidate (from this mix or the
        # scene pool) has led LEAST so far — least leads first, strongest
        # base intensity to break ties. That round-robins the scene's own
        # scents: rain can return as a refrain after everything else had a
        # turn, but never hogs consecutive frames. The bridge emits by max
        # intensity, so promotion must out-rank the repeat to change what
        # sprays; inserting first also wins exact ties at the curve peak.
        top = keep_strongest(mix) or {}
        if top.get("odor") and (top["odor"] == last_lead or top["odor"] in used):
            cands: dict[str, dict] = {}
            for s in mix + pool:
                prev = cands.get(s["odor"])
                if prev is None or s["intensity"] > prev["intensity"]:
                    cands[s["odor"]] = dict(s)
            ranked = [c for c in cands.values() if c["odor"] != last_lead]
            if ranked:
                fresh = min(ranked, key=lambda c: (lead_counts.get(c["odor"], 0),
                                                   -c["intensity"]))
                if fresh["intensity"] <= top["intensity"]:
                    fresh["intensity"] = round(min(1.0, top["intensity"] + 0.05), 3)
                mix = normalize_mix([fresh] + mix)[:MIX_SIZE]
        top = keep_strongest(mix) or {}
        cause = (top.get("why") or "").strip()
        frames.append({"frame": idx, "t_seconds": round(idx * FRAME_INTERVAL, 3),
                       "mix": mix, "cause": cause})
        if top.get("odor"):
            recent_leads.append(top["odor"])
            last_lead = top["odor"]
            lead_counts[top["odor"]] = lead_counts.get(top["odor"], 0) + 1
    if sniffer is not None and failed_frames == FRAME_COUNT:
        say(f"  model answered none of {FRAME_COUNT} frames; whole track is "
          f"rule-based (check the model server)")
    return frames


# ─────────────────────────────── delivery ────────────────────────────────────
# Transport is the omara bridge's WebSocket API (omara_bridge.py, default
# ws://127.0.0.1:8765). One "spray" command per mix fires EVERY channel of
# that mix in one packet, each at its own intensity — the bridge resolves
# names against loaded tubes and reports picks it had to skip. The bridge
# also pushes events (hello/ready/battery/error) asynchronously to all
# clients, so replies are matched by the "ok" key, not by message order.

def _recv_reply(ws, timeout: float) -> dict:
    """Read until a reply ({ok:...}) arrives; async bridge events in between
    are skipped."""
    deadline = time.monotonic() + timeout
    while True:
        remaining = max(0.5, deadline - time.monotonic())
        try:
            raw = ws.recv(timeout=remaining)
        except TypeError:                    # sync client without recv timeout
            raw = ws.recv()
        msg = json.loads(raw)
        if isinstance(msg, dict) and "ok" in msg:
            return msg

def bridge_connection(url: str):
    """A WebSocket connection to the bridge, usable as a context manager
    (`with bridge_connection(url) as ws:`). The hello event needs no special
    handling: _recv_reply ignores any message without an 'ok' key."""
    if ws_connect is None:
        raise RuntimeError("websockets is required to reach the bridge "
                           "(pip install -r requirements.txt)")
    token = os.environ.get("OMARA_BRIDGE_TOKEN")
    headers = {"Authorization": f"Bearer {token}"} if token else None
    return ws_connect(url, open_timeout=5.0, additional_headers=headers)

def spray_mix(ws, mix: list[dict]) -> dict:
    """Spray one mix: every channel fires in ONE packet at its own intensity."""
    scents = [[s["odor"], s["intensity"]] for s in mix]
    ws.send(json.dumps({"cmd": "spray", "scents": scents,
                        "algorithm": "average"}))
    return _recv_reply(ws, timeout=15.0)

def play_track(frames: list[dict], url: str) -> tuple[int, int]:
    """Send each keyframe's mix to the bridge at its scheduled time over one
    persistent connection. Every channel of a mix sprays with its own
    intensity; channels not on the cartridge are reported as skipped."""
    sent = failed = 0
    total = len(frames)
    with bridge_connection(url) as ws:
        t_start = time.monotonic()
        for frame in frames:
            target = t_start + frame["t_seconds"]
            now = time.monotonic()
            if target > now:
                time.sleep(target - now)
            try:
                reply = spray_mix(ws, frame["mix"])
                if not reply.get("ok"):
                    raise RuntimeError(str(reply))
                sent += 1
                parts = ", ".join(f"{s['odor']}@{s['intensity']:.2f}"
                                  for s in frame["mix"])
                cause = frame.get("cause") or ""
                skipped = reply.get("skipped") or []
                label = (f"  frame {frame['frame'] + 1:2d}/{total} @ "
                         f"{frame['t_seconds']:4.0f}s " if total > 1 else "  ")
                say(f"{label}sprayed {parts}"
                    + (f"   because: {cause}" if cause else "")
                    + (f"   NOT LOADED, skipped: {', '.join(skipped)}"
                       if skipped else ""))
            except Exception as exc:
                failed += 1
                say(f"  frame {frame['frame'] + 1:2d}/{total} FAILED to reach "
                    f"bridge: {exc}")
    return sent, failed


# ─────────────────────── safe-space reference file (recall) ──────────────────
# The calculated scent + the client's own words are saved to safe_space.json.
# On a later run, session.py finds it and asks whether to RETURN TO YOUR SAFE
# SPACE: yes re-sprays the saved mix and recites what is in the file; no runs
# a fresh intake. Recall text quotes only saved data — nothing invented.

_RECALL_KEYS = (("place", "Place"), ("sound", "Sounds"), ("smell", "Smells"),
                ("touch", "Feels"), ("company", "Company"),
                ("color_time", "Light and color"), ("emotion", "Feeling"))

def save_safe_space(args: argparse.Namespace, profile: dict,
                    mix: list[dict], track: list[dict] | None = None) -> None:
    doc = {"saved_at": time.strftime("%Y-%m-%d %H:%M:%S"),
           "keyframes": args.keyframes,
           "profile": profile, "mix": mix}
    if track is not None:
        doc["track"] = track
    try:
        with open(args.safe_space, "w", encoding="utf-8") as fh:
            json.dump(doc, fh, indent=2)
        say(f"Saved your safe-space scent to {args.safe_space}")
    except OSError as exc:
        say(f"WARNING: could not save the reference file: {exc}")

def load_safe_space(args: argparse.Namespace) -> dict | None:
    try:
        with open(args.safe_space, "r", encoding="utf-8") as fh:
            doc = json.load(fh)
        if isinstance(doc, dict) and doc.get("mix"):
            return doc
    except FileNotFoundError:
        return None
    except (OSError, json.JSONDecodeError) as exc:
        say(f"Saved safe space unreadable ({exc}); starting fresh instead.")
    return None

def recall_text(doc: dict) -> str:
    """The 'remember ... to set the scene' line, built ONLY from saved data."""
    mix = doc.get("mix") or []
    scents = " + ".join(f"{s['odor']}@{s['intensity']:.2f}" for s in mix)
    profile = doc.get("profile") or {}
    lines = [wrap(f"Remember: {scents} to set the scene with the stuff you "
                  "told it:")] if scents else ["Remember your safe space:"]
    for key, label in _RECALL_KEYS:
        val = str(profile.get(key, "")).strip()
        if val:
            lines.append(wrap(f"  {label}: {val}", width=68))
    return "\n".join(lines)

def try_recall(args: argparse.Namespace) -> int | None:
    """Ask the saved safe space. Returns an exit code if a recall ran, or
    None to fall through to a fresh intake."""
    if args.skip_recall:
        return None
    doc = load_safe_space(args)
    if doc is None:
        return None
    say()
    mix_line = ", ".join(f"{s['odor']}@{s['intensity']:.2f}"
                         for s in doc["mix"])
    saved_at = str(doc.get("saved_at") or "an earlier session")
    saved_place = str((doc.get("profile") or {}).get("place", "")).strip()
    on_file = f"A safe space is on file from {saved_at}: {mix_line}"
    if saved_place:
        on_file += f" ({saved_place})"
    say(wrap(on_file))
    if not confirm("Would you like to return to your safe space?", True):
        return None
    say()
    say(recall_text(doc))
    say()
    if args.preview:
        say("--preview: nothing was sent.")
        return 0
    if not confirm("Spray the saved mix too?", True):
        say("No spray — but the words above are still yours to remember.")
        return 0
    try:
        with bridge_connection(args.bridge_url) as ws:
            reply = spray_mix(ws, doc["mix"])
        if not reply.get("ok"):
            raise RuntimeError(str(reply))
        skipped = reply.get("skipped") or []
        say("Sprayed. Breathe slowly; stay with the place."
            + (f"   NOT LOADED, skipped: {', '.join(skipped)}" if skipped
               else ""))
        return 0
    except Exception as exc:
        say(f"ERROR: bridge unreachable at {args.bridge_url}: {exc}")
        say("Start it first: run.bat   (leave its window open), then rerun.")
        say("No spray — but the words above are still yours to remember.")
        return 1


# ──────────────────────────────── session ────────────────────────────────────
def run_session(args: argparse.Namespace) -> int:
    rc = try_recall(args)
    if rc is not None:
        return rc

    profile = run_intake()

    sniffer: Sniffer | None = None
    if not args.no_model:
        try:
            sniffer = Sniffer(args.base_url, args.model, args.palette,
                              timeout=args.model_timeout)
            say(f"[model] {args.model} @ {args.base_url}")
        except Exception as exc:
            say(f"[model] unavailable ({exc}); building rule-based track")

    t0 = time.monotonic()
    if args.keyframes <= 1:
        say()
        say(f"Generating your safe-space scent mix "
            f"({MIX_SIZE} channels, each with its own intensity)...")
        mix = build_scene_mix(profile, sniffer)
        dt = time.monotonic() - t0
        for s in mix:
            why = (s.get("why") or "").strip()
            say(f"  {s['odor']}@{s['intensity']:.2f}"
                + (f"   because: {why}" if why else ""))
        say(f"Mix built in {dt:.1f}s.")

        if args.preview:
            say("--preview: nothing was sent, nothing saved.")
            return 0
        save_safe_space(args, profile, mix)
        if not confirm(f"Spray it now through the bridge at "
                       f"{args.bridge_url}?", True):
            say("Not spraying. Re-run start_session.bat when ready.")
            return 0
        frames = [{"frame": 0, "t_seconds": 0.0, "mix": mix,
                   "cause": ""}]
    else:
        say()
        say(f"Generating {args.keyframes}-frame safe-space sequence "
            f"({FRAME_INTERVAL:.0f}s interval, {MIX_SIZE} scents per "
            f"frame)...")
        frames = build_track(profile, sniffer, args.keyframes)
        dt = time.monotonic() - t0
        say(f"Track built in {dt:.1f}s. Every channel of every frame's mix "
            f"sprays with its own intensity.")

        if args.preview:
            for f in frames:
                parts = ", ".join(f"{s['odor']}@{s['intensity']:.2f}"
                                  for s in f["mix"])
                cause = f.get("cause") or ""
                say(f"  frame {f['frame'] + 1:2d}/{args.keyframes} @ "
                    f"{f['t_seconds']:4.0f}s {parts}"
                    + (f"   because: {cause}" if cause else ""))
            say("--preview: nothing was sent, nothing saved.")
            return 0

        first = frames[0]["mix"] if frames else []
        save_safe_space(args, profile, first, track=frames)

        if not confirm(f"Play it now through the bridge at "
                       f"{args.bridge_url}?", True):
            say("Not playing. Re-run start_session.bat when ready.")
            return 0

    try:
        with bridge_connection(args.bridge_url):
            pass
    except Exception as exc:
        say(f"ERROR: bridge unreachable at {args.bridge_url}: {exc}")
        say("Start it first: run.bat   (leave its window open), then rerun.")
        return 1

    say()
    if len(frames) > 1:
        say(wrap("Playing now. Sit back and stay with your safe place; "
                 f"breathe slowly. The sequence lasts about "
                 f"{len(frames) * FRAME_INTERVAL:.0f} seconds."))
    else:
        say(wrap("Spraying now. Sit back and stay with your safe place; "
                 "breathe slowly."))
    say()
    sent, failed = play_track(frames, args.bridge_url)
    say()
    unit = "mix" if len(frames) <= 1 else "frames"
    say(f"Session complete: {sent}/{len(frames)} {unit} delivered to Omara"
        + (f", {failed} failed" if failed else "."))
    say("You can return to this place any time — close your eyes and "
        "breathe it in.")
    return 0 if failed == 0 else 2


def main() -> int:
    ap = argparse.ArgumentParser(
        description="EMDR safe-space session runner (SoothingSpaces)")
    def keyframes_arg(raw: str) -> int:
        try:
            n = int(raw)
        except ValueError:
            raise argparse.ArgumentTypeError(
                "--keyframes needs a whole number") from None
        if not 1 <= n <= MAX_KEYFRAMES:
            raise argparse.ArgumentTypeError(
                f"--keyframes must be between 1 and {MAX_KEYFRAMES}")
        return n
    ap.add_argument("--keyframes", type=keyframes_arg, default=DEFAULT_KEYFRAMES,
                    help="1 (default): one scent mix for the scene, every "
                         "channel spraying at its own intensity. N>1: a "
                         "multi-frame keyframe track, one mix per frame.")
    ap.add_argument("--bridge-url", default="ws://127.0.0.1:8765",
                    help="omara bridge WebSocket (session.py talks to this)")
    ap.add_argument("--base-url", default="http://127.0.0.1:8888/v1",
                    help="OpenAI-compatible model server; Ollama is :11434/v1")
    ap.add_argument("--model", default="unsloth/Qwen3.8-Flash-Next-GGUF")
    ap.add_argument("--palette", default=os.path.join(
        os.path.dirname(os.path.abspath(__file__)), "palette.txt"))
    ap.add_argument("--safe-space", default=SAFE_SPACE_FILE, metavar="FILE",
                    help="reference file for the calculated scent "
                         "(default safe_space.json)")
    ap.add_argument("--skip-recall", action="store_true",
                    help="ignore the saved safe space; go straight to intake")
    ap.add_argument("--model-timeout", type=float, default=25.0)
    ap.add_argument("--no-model", action="store_true",
                    help="skip the model; build the track from palette rules")
    ap.add_argument("--preview", action="store_true",
                    help="build and print; send nothing, save nothing "
                         "(test mode)")
    args = ap.parse_args()

    for stream in (sys.stdout, sys.stderr):
        try:
            stream.reconfigure(encoding="utf-8", errors="replace")
        except Exception:
            pass
    try:
        return run_session(args)
    except KeyboardInterrupt:
        say("\nSession ended by user.")
        return 130


if __name__ == "__main__":
    raise SystemExit(main())
